<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BarangSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('barangs')->insert([
            // LAB PPLG 1
            [
                'kode_barang' => 'P1001',
                'nama_barang' => 'Proyektor',
                'kategori_id' => 6,
                'lokasi_id' => 1,
                'sumber_dana_id' => 1,
                'jumlah' => 1,
                'satuan' => 'Unit',
                'detail_kondisi' => json_encode(['Baik' => 1]),
                'tanggal_pengadaan' => '2023-05-15',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'K1001',
                'nama_barang' => 'Komputer',
                'kategori_id' => 6,
                'lokasi_id' => 1,
                'sumber_dana_id' => 1,
                'jumlah' => 30,
                'satuan' => 'Unit',
                'detail_kondisi' => json_encode(['Baik' => 30]),
                'tanggal_pengadaan' => '2023-06-01',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'M1001',
                'nama_barang' => 'Mouse',
                'kategori_id' => 3,
                'lokasi_id' => 1,
                'sumber_dana_id' => 1,
                'jumlah' => 30,
                'satuan' => 'Unit',
                'detail_kondisi' => json_encode(['Baik' => 30]),
                'tanggal_pengadaan' => '2023-06-05',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'M2001',
                'nama_barang' => 'Meja',
                'kategori_id' => 4,
                'lokasi_id' => 1,
                'sumber_dana_id' => 1,
                'jumlah' => 30,
                'satuan' => 'Unit',
                'detail_kondisi' => json_encode(['Baik' => 30]),
                'tanggal_pengadaan' => '2023-06-10',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'K2001',
                'nama_barang' => 'Kursi',
                'kategori_id' => 4,
                'lokasi_id' => 1,
                'sumber_dana_id' => 1,
                'jumlah' => 30,
                'satuan' => 'Unit',
                'detail_kondisi' => json_encode(['Baik' => 30]),
                'tanggal_pengadaan' => '2023-06-10',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // LAB PPLG 2
            [
                'kode_barang' => 'P1002',
                'nama_barang' => 'Proyektor',
                'kategori_id' => 6,
                'lokasi_id' => 2,
                'sumber_dana_id' => 1,
                'jumlah' => 1,
                'satuan' => 'Unit',
                'detail_kondisi' => json_encode(['Baik' => 1]),
                'tanggal_pengadaan' => '2023-05-15',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'K1002',
                'nama_barang' => 'Komputer',
                'kategori_id' => 6,
                'lokasi_id' => 2,
                'sumber_dana_id' => 1,
                'jumlah' => 30,
                'satuan' => 'Unit',
                'detail_kondisi' => json_encode(['Baik' => 30]),
                'tanggal_pengadaan' => '2023-06-01',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'M1002',
                'nama_barang' => 'Mouse',
                'kategori_id' => 3,
                'lokasi_id' => 2,
                'sumber_dana_id' => 1,
                'jumlah' => 30,
                'satuan' => 'Unit',
                'detail_kondisi' => json_encode(['Baik' => 30]),
                'tanggal_pengadaan' => '2023-06-05',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'M2002',
                'nama_barang' => 'Meja',
                'kategori_id' => 4,
                'lokasi_id' => 2,
                'sumber_dana_id' => 1,
                'jumlah' => 30,
                'satuan' => 'Unit',
                'detail_kondisi' => json_encode(['Baik' => 30]),
                'tanggal_pengadaan' => '2023-06-10',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'K2002',
                'nama_barang' => 'Kursi',
                'kategori_id' => 4,
                'lokasi_id' => 2,
                'sumber_dana_id' => 1,
                'jumlah' => 30,
                'satuan' => 'Unit',
                'detail_kondisi' => json_encode(['Baik' => 30]),
                'tanggal_pengadaan' => '2023-06-10',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // LAB PPLG 3
            [
                'kode_barang' => 'P1003',
                'nama_barang' => 'Proyektor',
                'kategori_id' => 6,
                'lokasi_id' => 3,
                'sumber_dana_id' => 1,
                'jumlah' => 1,
                'satuan' => 'Unit',
                'detail_kondisi' => json_encode(['Baik' => 1]),
                'tanggal_pengadaan' => '2023-05-15',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'K1003',
                'nama_barang' => 'Komputer',
                'kategori_id' => 6,
                'lokasi_id' => 3,
                'sumber_dana_id' => 1,
                'jumlah' => 30,
                'satuan' => 'Unit',
                'detail_kondisi' => json_encode(['Baik' => 30]),
                'tanggal_pengadaan' => '2023-06-01',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'M1003',
                'nama_barang' => 'Mouse',
                'kategori_id' => 3,
                'lokasi_id' => 3,
                'sumber_dana_id' => 1,
                'jumlah' => 30,
                'satuan' => 'Unit',
                'detail_kondisi' => json_encode(['Baik' => 30]),
                'tanggal_pengadaan' => '2023-06-05',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'M2003',
                'nama_barang' => 'Meja',
                'kategori_id' => 4,
                'lokasi_id' => 3,
                'sumber_dana_id' => 1,
                'jumlah' => 30,
                'satuan' => 'Unit',
                'detail_kondisi' => json_encode(['Baik' => 30]),
                'tanggal_pengadaan' => '2023-06-10',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'K2003',
                'nama_barang' => 'Kursi',
                'kategori_id' => 4,
                'lokasi_id' => 3,
                'sumber_dana_id' => 1,
                'jumlah' => 30,
                'satuan' => 'Unit',
                'detail_kondisi' => json_encode(['Baik' => 30]),
                'tanggal_pengadaan' => '2023-06-10',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // RUANG UKS
            [
                'kode_barang' => 'P1004',
                'nama_barang' => 'Proyektor',
                'kategori_id' => 6,
                'lokasi_id' => 4,
                'sumber_dana_id' => 1,
                'jumlah' => 1,
                'satuan' => 'Unit',
                'detail_kondisi' => json_encode(['Baik' => 1]),
                'tanggal_pengadaan' => '2023-05-15',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'K1004',
                'nama_barang' => 'Komputer',
                'kategori_id' => 6,
                'lokasi_id' => 4,
                'sumber_dana_id' => 1,
                'jumlah' => 30,
                'satuan' => 'Unit',
                'detail_kondisi' => json_encode(['Baik' => 30]),
                'tanggal_pengadaan' => '2023-06-01',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'M1004',
                'nama_barang' => 'Mouse',
                'kategori_id' => 3,
                'lokasi_id' => 4,
                'sumber_dana_id' => 1,
                'jumlah' => 30,
                'satuan' => 'Unit',
                'detail_kondisi' => json_encode(['Baik' => 30]),
                'tanggal_pengadaan' => '2023-06-05',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'M2004',
                'nama_barang' => 'Meja',
                'kategori_id' => 4,
                'lokasi_id' => 4,
                'sumber_dana_id' => 1,
                'jumlah' => 30,
                'satuan' => 'Unit',
                'detail_kondisi' => json_encode(['Baik' => 30]),
                'tanggal_pengadaan' => '2023-06-10',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'K2004',
                'nama_barang' => 'Kursi',
                'kategori_id' => 4,
                'lokasi_id' => 4,
                'sumber_dana_id' => 1,
                'jumlah' => 30,
                'satuan' => 'Unit',
                'detail_kondisi' => json_encode(['Baik' => 30]),
                'tanggal_pengadaan' => '2023-06-10',
                'gambar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
